version: '3'

services:
  database:
    image: 'bitnami/postgresql:latest'
    ports:
      - '50000:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - persona-pro-network

networks:
  persona-pro-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
